### ISSUE TITLE
Migration to .Net Core

### ISSUE THREAD

**Issue by blazej-kosmowski** [appium/dotnet-client#595]
I hope this message finds you well. I noticed that your project is currently built on the .NET Framework and wanted to suggest a migration to .NET Core as a framework for your project.

Would you be open to considering a migration to .NET Core in the near future?

Best regards,

**Comment by Dor-bl** [comment]
Hi @blazej-kosmowski ,
This is indeed something we would like to do.
But since I'm currently the main contributor to this project and the fact I don't have enough capacity, not to mention there are other bugs/features that are more important to work on in order for us to exit the beta stages of version 5 we will have to put this feature request on hold for a while.
